export default {
   GET_ALL_GROUPS: 'get_all_groups',
   GET_CREATED_GROUPS: 'get_created_groups',
   GET_JOINED_GROUPS: 'get_joined_groups',
   CREATE_NEW_GROUP: 'create_new_group',
   GET_USER_INFO: 'get_user_info',
   EDIT_USER_INFO: 'edit_user_info',
   LOGIN_APP: 'login_app',
   GET_GROUP_DETAILS: 'get_group_details',
   EDIT_GROUP_INFO: 'edit_group_info',
   CREATE_ACCOUNT: 'create_account',
   GET_USER_ID: 'get_user_id',
   ERROR_LOGIN: 'error_login',
    JOIN_GROUP: 'join_group',
   USERNAME_ALREADY_EXISTS: 'username_already_exists',
   EMAIL_ALREADY_EXISTS: 'email_already_exists',
   USERNAME_AND_EMAIL_EXIST: 'username_and_email_exist',
   GROUPNAME_ALREADY_EXIST: 'groupname_already_exist',
   VALID_GROUPNAME: 'valid_groupname',
}